- package:
  - name: cardano-wallet-byron
  - section:
    - name: bench:restore
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Wallet.Primitive.AddressDiscovery.Any.TH
        - identifier:
          - AnyAddressStateId
          - AnyAddressStateKey
          - AnyAddressStateProportion
  - section:
    - name: test:integration bench:latency
    - message:
      - name: Module reused between components
      - module:
        - Cardano.Wallet.Byron.Faucet
- package:
  - name: cardano-wallet-core
  - section:
    - name: test:unit
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Pool.MetricsSpec
        - identifier:
          - RegistrationsTest
          - arbitraryChunks
      - module:
        - name: Cardano.Wallet.DB.StateMachine
        - identifier: showLabelledExamples
      - module:
        - name: Spec
        - identifier: main
  - section:
    - name: test:unit bench:db
    - message:
      - name: Module reused between components
      - module: Cardano.Wallet.DummyTarget.Primitive.Types
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Wallet.DummyTarget.Primitive.Types
        - identifier: genesisHash
- package:
  - name: cardano-wallet-jormungandr
  - section:
    - name: test:jormungandr-integration
    - message:
      - name: Redundant build-depends entry
      - depends:
        - aeson-qq
        - cryptonite
        - exceptions
        - generic-arbitrary
        - lifted-base
        - monad-control
        - persistent
        - safe
        - template-haskell
        - time
        - warp
        - yaml
  - section:
    - name: test:jormungandr-integration bench:latency
    - message:
      - name: Module reused between components
      - module:
        - Cardano.Wallet.Jormungandr.Faucet
        - Cardano.Wallet.Jormungandr.Launch
        - Test.Integration.Jcli
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Wallet.Jormungandr.Faucet
        - identifier: genFaucets
      - module:
        - name: Cardano.Wallet.Jormungandr.Launch
        - identifier: withBackendOnly
  - section:
    - name: test:unit
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Wallet.Jormungandr.NetworkSpec
        - identifier:
          - C
          - Consumer
          - MockBlock
          - 'N'
          - Node
          - NodeAddBlocks
          - NodeGarbageCollect
          - NodeOp
          - NodeRewind
          - S
          - TestNetworkLayer
          - addGaps
          - applyNodeOp
          - applyNodeOps
          - block0
          - block0H
          - consumerRestoreStep
          - emptyNode
          - fromJBlock
          - genBlocks
          - genBlocksWith
          - genCheckpoints
          - genConsumer
          - genGC
          - genGaps
          - genNodeOp
          - genNodeOps
          - genRewind
          - genSwitchChain
          - genesisHash
          - getNodeChain
          - getNodeTip
          - isNodeAddBlocks
          - isNodeRewindOf
          - mockBlockHash
          - mockJormungandrClient
          - mockNetworkLayer
          - nodeAddBlocks
          - nodeGarbageCollect
          - nodeRewind
          - parentGenesisHash
          - prop_generator
          - prop_sync
          - removeNoOp
          - shiftOp
          - showBlock
          - showChain
          - showCheckpoints
          - showHash
          - toJBlock
- package:
  - name: cardano-wallet-launcher
  - section:
    - name: library
    - message:
      - name: Module not compiled
      - module: Cardano.Startup.Windows
