

services:
  cardano-node:
    container_name: cardano-node-on-${WALLET_PORT:-8090}
    image: cardanofoundation/cardano-wallet:${WALLET_TAG}
    volumes:
      - ${NODE_DB}:/data
      - ${NODE_SOCKET_DIR}:/ipc
      - ./configs/cardano:/configs
    restart: on-failure
    user: ${USER_ID}
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    entrypoint: []

  cardano-wallet:
    container_name: cardano-wallet-on-${WALLET_PORT}
    image: cardanofoundation/cardano-wallet:${WALLET_TAG}
    volumes:
      - ${WALLET_DB}:/wallet-db
      - ${NODE_SOCKET_DIR}:/ipc
      - ./configs/cardano:/configs
    ports:
      - ${WALLET_PORT}:8090
    entrypoint: []
    user: ${USER_ID}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    environment:
      WALLET_PORT: ${WALLET_PORT:-8090}

  icarus:
    image: piotrstachyra/icarus:v2023-04-14
    container_name: icarus-on-${WALLET_PORT}
    network_mode: "host"
    restart: on-failure
    environment:
      WALLET_PORT: ${WALLET_PORT:-8090}
