


services:
  cardano-node:

    extends:
      file: docker-compose-common.yml
      service: cardano-node
    image: ghcr.io/intersectmbo/cardano-node:8.11.0-pre
    command: >
      cardano-node run --topology /configs/sanchonet/topology.json
        --database-path /data
        --socket-path /ipc/${NODE_SOCKET_NAME:-node.socket}
        --config /configs/sanchonet/config.json
        +RTS -N3

  cardano-wallet:

    extends:
      file: docker-compose-common.yml
      service: cardano-wallet

    command: >
      cardano-wallet serve
        --node-socket /ipc/${NODE_SOCKET_NAME:-node.socket}
        --database /wallet-db
        --listen-address 0.0.0.0
        --testnet /configs/sanchonet/byron-genesis.json
        +RTS -N3

  icarus:
    extends:
      file: docker-compose-common.yml
      service: icarus
