# This resolver file contains a ghc-8.10-based stackage LTS, with a
# released cardano-node version, and supporting libraries.
#
# NOTE: Remember to update the version matrix in README.md when
# bumping the Cardano version.
resolver: https://raw.githubusercontent.com/input-output-hk/cardano-haskell/65c9fb895ac74b3d2295466193a77328bcac836f/snapshots/cardano-1.28.0.yaml
compiler: ghc-8.10.5

packages:
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/numeric
- lib/text-class
- lib/test-utils
- lib/shelley
- lib/strict-non-empty-containers

allow-newer: true

extra-deps:
- OddWord-1.0.2.0
- command-0.1.1
- hspec-2.8.2
- hspec-core-2.8.2

# cardano-addresses-3.5.0
- git: https://github.com/input-output-hk/cardano-addresses
  commit: 46ce81050f4015abd40c6bdf0a1ed30fa54e375a
  subdirs:
    - command-line
    - core

flags:
  # Avoid a system library which causes difficulty with cross-compilation
  zip:
    disable-bzip2: true

  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

  # Using RDRAND instead of /dev/urandom as an entropy source for key
  # generation is dubious. Set the flag so we use /dev/urandom by default.
  cryptonite:
    support_rdrand: false

ghc-options:
  # Enable .hie file generation for weeder and haskell-language-server
  "$locals": -fwrite-ide-info

nix:
  shell-file: nix/stack-shell.nix
  # Disabling the pure nix-shell allows environment variables to be
  # passed down to tests. We need this for integration tests.
  pure: false
