resolver: lts-13.24
compiler: ghc-8.6.5

packages:
- lib/bech32
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/text-class
- lib/test-utils
- lib/jormungandr

extra-deps:
# Miscellaneous
- base58-bytestring-0.1.0
- quickcheck-state-machine-0.6.0
- command-0.1.1

# persistent-2.10.2 with CASCADE DELETE support for SQLite.
#
# See: https://github.com/input-output-hk/persistent/tree/cardano-wallet
- git: https://github.com/input-output-hk/persistent
  commit: 107787ecc4c8a112375493cd66574f788f950fce
  subdirs:
    - persistent
    - persistent-sqlite
    - persistent-template

# cardano-crypto
- git: https://github.com/input-output-hk/cardano-crypto
  commit: 3c5db489c71a4d70ee43f5f9b979fcde3c797f2a

# iohk-monitoring-framework
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: bd31cd2f3922010ddb76bb869f29c4e63bb8001b
  subdirs:
    - contra-tracer
    - iohk-monitoring
- time-units-1.0.0
- libsystemd-journal-1.4.4

flags:
  # Bring in less dependencies from iohk-monitoring
  iohk-monitoring:
    disable-ekg: true
    disable-examples: true
    disable-graylog: true
    disable-gui: true
    disable-prometheus: true
    disable-systemd: true

nix:
  shell-file: nix/stack-shell.nix
