resolver: lts-14.25

packages:
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/text-class
- lib/test-utils
- lib/jormungandr
- lib/byron

extra-deps:
# Miscellaneous
- base58-bytestring-0.1.0
- bech32-1.0.2
- bech32-th-1.0.2
- OddWord-1.0.2.0
- command-0.1.1
- wai-extra-3.0.29.1
- Win32-2.6.2.0

# Needed because network > 3.1 is needed for cardano-wallet-byron
- servant-0.17
- servant-server-0.17
- servant-client-core-0.17
- servant-client-0.17
- servant-swagger-1.1.8

# 'zip' with an extra flag to disable bzlib2 library
- zip-1.3.0

# persistent-2.10.2 with CASCADE DELETE support for SQLite.
#
# See: https://github.com/input-output-hk/persistent/tree/cardano-wallet
- git: https://github.com/input-output-hk/persistent
  commit: 107787ecc4c8a112375493cd66574f788f950fce
  subdirs:
    - persistent
    - persistent-sqlite
    - persistent-template

# cardano-crypto
- git: https://github.com/input-output-hk/cardano-crypto
  commit: 05aa1bc640c42bfca787531d12595489c1fa3b82

# iohk-monitoring-framework
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: 3e45d5dd4942c295f0ea4bfed7c407b914b15447
  subdirs:
    - contra-tracer
    - iohk-monitoring
    - plugins/backend-aggregation
    - plugins/backend-monitoring
    - tracer-transformers

# dependencies of iohk-monitoring-framework
- git: https://github.com/CodiePP/ekg-prometheus-adapter
  commit: 1a258b6df7d9807d4c4ff3e99722223d31a2c320
- prometheus-2.1.2
- time-units-1.0.0
- libsystemd-journal-1.4.4
- katip-0.8.3.0

# dependencies for cardano-wallet-byron
- streaming-binary-0.3.0.1
- generic-monoid-0.1.0.0
- canonical-json-0.6.0.0
- cborg-0.2.2.0
- statistics-linreg-0.3
- network-3.1.0.1
- connection-0.3.1
- Unique-0.4.7.6
- moo-1.2
- gray-code-0.3.1

# - bimap-0.4.0
# - hedgehog-1.0
# - tasty-hedgehog-1.0.0.1

- git: https://github.com/input-output-hk/cardano-base
  commit: f869bee9b08ba1044b1476737c9d65083e1c6c7f
  subdirs:
    - binary
    - binary/test
    - cardano-crypto-class
    - slotting

- git: https://github.com/input-output-hk/cardano-ledger
  commit: 1368966fd6d806d8eb65cd1ba193548c402355f6
  subdirs:
    - cardano-ledger
    - cardano-ledger/test
    - crypto
    - crypto/test

- git: https://github.com/input-output-hk/cardano-ledger-specs
  commit: 647cd71e3c4630488e71596f5e9c26fee598b541
  subdirs:
    - byron/semantics/executable-spec # small-steps
    - byron/ledger/executable-spec    # cs-ledger
    - byron/chain/executable-spec     # cs-blockchain

- git: https://github.com/input-output-hk/goblins
  commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

- git: https://github.com/input-output-hk/cardano-prelude
  commit: fe76ec64f6b45259cc407a6d840dad79ee6063b6
  subdirs:
    - .
    - test

- git: https://github.com/input-output-hk/ouroboros-network
  commit: a85bd4751ca5c81c0507482848358980814e9ca3
  subdirs:
    - io-sim
    - io-sim-classes
    - network-mux
    - ouroboros-network
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - typed-protocols
    - typed-protocols-examples
    - ouroboros-network-framework
    - ouroboros-network-testing
    - ntp-client
    - Win32-network

flags:
  # Avoid a system library which causes difficulty with cross-compilation
  zip:
    disable-bzip2: true

# Generate files required by Weeder.
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}

allow-newer: true

nix:
  shell-file: nix/stack-shell.nix
