resolver: lts-13.24

packages:
- lib/bech32
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/text-class
- lib/test-utils
- lib/jormungandr
- lib/byron

extra-deps:
# Miscellaneous
- base58-bytestring-0.1.0
- OddWord-1.0.2.0
- quickcheck-state-machine-0.6.0
- command-0.1.1
- clock-0.8

# 'zip' with an extra flag to disable bzlib2 library
- zip-1.3.0

# persistent-2.10.2 with CASCADE DELETE support for SQLite.
#
# See: https://github.com/input-output-hk/persistent/tree/cardano-wallet
- git: https://github.com/input-output-hk/persistent
  commit: 107787ecc4c8a112375493cd66574f788f950fce
  subdirs:
    - persistent
    - persistent-sqlite
    - persistent-template

# cardano-crypto
- git: https://github.com/input-output-hk/cardano-crypto
  commit: 3c5db489c71a4d70ee43f5f9b979fcde3c797f2a

# iohk-monitoring-framework
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: b4643defabb23b3d78f4b690a01bb6a41a3cd203
  subdirs:
    - contra-tracer
    - iohk-monitoring
    - plugins/backend-aggregation
    - plugins/backend-monitoring
    # - plugins/backend-editor
    # - plugins/backend-ekg
    # - plugins/scribe-systemd
# dependencies of iohk-monitoring-framework
- git: https://github.com/CodiePP/ekg-prometheus-adapter
  commit: 1a258b6df7d9807d4c4ff3e99722223d31a2c320
- prometheus-2.1.2
- time-units-1.0.0
- libsystemd-journal-1.4.4
- katip-0.8.3.0

# dependencies for cardano-wallet-shelley
- tasty-hedgehog-1.0.0.1
- streaming-binary-0.3.0.1
- hedgehog-1.0
- generic-monoid-0.1.0.0
- bimap-0.4.0@sha256:c59d587b56b575c299ba0c2fff44e630991a120a167de5a19cd7a81320f63c84,1717
- canonical-json-0.6.0.0@sha256:9021f435ccb884a3b4c55bcc6b50eb19d5fc3cc3f29d5fcbdef016f5bbae23a2,3488
- cborg-0.2.2.0@sha256:eaee50d09d766af95ba18348e4fc230243033b98633ed46ccb5ae85efef7dc6c,4779
- statistics-linreg-0.3@sha256:95c6efe6c7f6b26bc6e9ada90ab2d18216371cf59a6ef2b517b4a6fd35d9a76f,2544

- git: https://github.com/input-output-hk/cardano-base
  commit: 468d9b79ae3ac28f5f2cbb3ce52623a69923c4ef
  subdirs:
    - binary
    - binary/test
    - cardano-crypto-class
    - slotting

- git: https://github.com/input-output-hk/cardano-ledger
  commit: dbdb643722e431e4d232345a0eafdc7bdeab7b60
  subdirs:
    - cardano-ledger
    - cardano-ledger/test
    - crypto
    - crypto/test

- git: https://github.com/input-output-hk/cardano-prelude
  commit: 3c40edcf5bdba8721d3430d0aaaeea8770ce9bec
  subdirs:
    - .
    - test

- git: https://github.com/input-output-hk/ouroboros-network
  commit: c785fe64445357b806c847fa438fc7612563b42b
  subdirs:
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-consensus
      - typed-protocols
      - typed-protocols-cbor

flags:
  # Avoid a system library which causes difficulty with cross-compilation
  zip:
    disable-bzip2: true

# Generate files required by Weeder.
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}

nix:
  shell-file: nix/stack-shell.nix
