########################################################################
# The Stack build, with dependencies based on a Stackage LTS snapshot.
#
# * If changing this file, usually cabal.project should be updated too.
#
# * When changing something here, check https://www.stackage.org/lts
#   for new releases, and update the resolver version to be the latest
#   in whichever series uses GHC 8.10.x.
#
# * After changing dependencies in stack.yaml or *.cabal, you must run
#   ./nix/regenerate.sh to update Nix files. Alternatively, let
#   Buildkite CI update the files for you.
#
########################################################################

resolver: lts-18.5
compiler: ghc-8.10.5

packages:
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/numeric
- lib/text-class
- lib/test-utils
- lib/shelley
- lib/strict-non-empty-containers

flags:
  # Avoid a system library which causes difficulty with cross-compilation
  zip:
    disable-bzip2: true

  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

  # Using RDRAND instead of /dev/urandom as an entropy source for key
  # generation is dubious. Set the flag so we use /dev/urandom by default.
  cryptonite:
    support_rdrand: false

ghc-options:
  # Enable .hie file generation for weeder and haskell-language-server
  "$locals": -fwrite-ide-info

nix:
  shell-file: nix/stack-shell.nix
  # Disabling the pure nix-shell allows environment variables to be
  # passed down to tests. We need this for integration tests.
  pure: false

allow-newer: true

extra-deps:
########################################################################
### cardano-wallet-specific dependencies

- OddWord-1.0.2.0
- command-0.1.1
- hspec-2.8.2
- hspec-core-2.8.2

# cardano-addresses-3.5.0
- git: https://github.com/input-output-hk/cardano-addresses
  commit: 46ce81050f4015abd40c6bdf0a1ed30fa54e375a
  subdirs:
    - command-line
    - core

########################################################################
### cardano-node 1.29.0-rc1 and its dependencies

- Cabal-3.4.0.0 # 3.2.1.0 on lts-18.5
- containers-0.5.11.0 # 0.6.2.1 on lts-18.5
- dns-3.0.4 # 4.0.1 on lts-18.5
- network-3.1.2.1 # 3.1.1.1 on lts-18.5
- recursion-schemes-5.1.3 # 5.2.2.1 on lts-18.5
- text-1.2.4.0 # 1.2.4.1 on lts-18.5
- Win32-2.6.2.0 # 2.6.1.0 on lts-18.5

# Same as on lts-18.5, but somehow stack requires it here
- binary-0.8.8.0
- parsec-3.1.14.0

# Not in LTS 18.5
- async-timer-0.2.0.0
- beam-core-0.9.1.0
- beam-migrate-0.5.1.0
- beam-sqlite-0.5.1.0
- canonical-json-0.6.0.0
- composition-prelude-3.0.0.2
- constraints-extras-0.3.1.0
- ip-1.5.1
- gray-code-0.3.1
- lazy-search-0.1.2.1
- lazysmallcheck-0.6
- libsystemd-journal-1.4.4
- markov-chain-usage-model-0.0.0
- micro-recursion-schemes-5.0.2.2
- monoidal-containers-0.6.0.1
- moo-1.2
- nothunks-0.1.2
- partial-order-0.2.0.0
- quickcheck-state-machine-0.7.0
- regex-posix-clib-2.7
- row-types-1.0.1.0
- servant-subscriber-0.7.0.0
- servant-websockets-2.0.0
- size-based-0.1.2.0
- statistics-linreg-0.3
- streaming-binary-0.2.2.0
- time-interval-0.1.1
- time-out-0.2
- transformers-except-0.1.1
- Unique-0.4.7.6

  # Using a fork until our patches can be merged upstream
- git: https://github.com/input-output-hk/criterion
  commit: fb2e7be532db96255d203f86360230cae37130f3

  # Using a fork until our patches can be merged upstream
- git: https://github.com/input-output-hk/optparse-applicative
  commit: 84bcc6f18992a441886589a117249bfface8630e

- git: https://github.com/input-output-hk/cardano-base
  commit: cb0f19c85e5bb5299839ad4ed66af6fa61322cc4
  subdirs:
  - base-deriving-via
  - binary
  - binary/test
  - cardano-crypto-class
  - cardano-crypto-praos
  - cardano-crypto-tests
  - orphans-deriving-via
  - slotting
  - strict-containers
  - measures

- git: https://github.com/input-output-hk/cardano-crypto
  commit: 07397f0e50da97eaa0575d93bee7ac4b2b2576ec

- git: https://github.com/input-output-hk/cardano-ledger-specs
  commit: d5b184a820853c7ba202efd615b8fadca1acb52c
  subdirs:
  - alonzo/impl
  - alonzo/test
  - byron/chain/executable-spec
  - byron/crypto
  - byron/crypto/test
  - byron/ledger/executable-spec
  - byron/ledger/impl
  - byron/ledger/impl/test
  - cardano-ledger-core
  - semantics/executable-spec
  - semantics/small-steps-test
  - shelley/chain-and-ledger/dependencies/non-integer
  - shelley/chain-and-ledger/executable-spec
  - shelley/chain-and-ledger/shelley-spec-ledger-test
  - shelley-ma/impl
  - shelley-ma/shelley-ma-test

- git: https://github.com/input-output-hk/cardano-node
  commit: 9a6a6c81e3aebfaf757b562c823146c7da601e1c
  subdirs:
  - cardano-api
  - cardano-cli
  - cardano-config
  - cardano-node

- git: https://github.com/input-output-hk/cardano-prelude
  commit: fd773f7a58412131512b9f694ab95653ac430852
  subdirs:
  - cardano-prelude
  - cardano-prelude-test

- git: https://github.com/input-output-hk/cardano-sl-x509
  commit: 12925934c533b3a6e009b61ede555f8f26bac037

- git: https://github.com/michaelpj/flat.git
  commit: ee59880f47ab835dbd73bea0847dab7869fc20d8

- git: https://github.com/input-output-hk/goblins
  commit: cde90a2b27f79187ca8310b6549331e59595e7ba

- git: https://github.com/input-output-hk/hedgehog-extras
  commit: edf6945007177a638fbeb8802397f3a6f4e47c14

- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: 808724ff8a19a33d0ed06f9ef59fbd900b08553c
  subdirs:
  - contra-tracer
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-ekg
  - plugins/backend-monitoring
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - tracer-transformers

- git: https://github.com/shmish111/purescript-bridge.git
  commit: 6a92d7853ea514be8b70bab5e72077bf5a510596

- git: https://github.com/input-output-hk/ouroboros-network
  commit: d070bad7ce389a4b2ff7fb4fcb7937fdeca80f3a
  subdirs:
  - io-classes
  - io-sim
  - monoidal-synchronisation
  - network-mux
  - ouroboros-consensus
  - ouroboros-consensus-test
  - ouroboros-consensus-byron
  - ouroboros-consensus-byronspec
  - ouroboros-consensus-byron-test
  - ouroboros-consensus-shelley
  - ouroboros-consensus-shelley-test
  - ouroboros-consensus-cardano
  - ouroboros-consensus-cardano-test
  - ouroboros-network
  - ouroboros-network-framework
  - ouroboros-network-testing
  - typed-protocols
  - typed-protocols-examples
  # Extra packages not used by cardano-node but used by cardano-wallet
  - cardano-client
  - ntp-client
  - ouroboros-consensus-mock

- git: https://github.com/input-output-hk/plutus
  commit: 8c83c4abe211b4bbcaca3cdf1b2c0e38d0eb683f
  subdirs:
    - freer-extras
    - playground-common
    - plutus-chain-index
    - plutus-contract
    - plutus-core
    - plutus-ledger
    - plutus-ledger-api
    - plutus-pab
    - plutus-tx
    - plutus-tx-plugin
    - plutus-use-cases
    - prettyprinter-configurable
    - quickcheck-dynamic
    - word-array

- git: https://github.com/shmish111/servant-purescript.git
  commit: a76104490499aa72d40c2790d10e9383e0dbde63

- git: https://github.com/input-output-hk/Win32-network
  commit: 3825d3abf75f83f406c1f7161883c438dac7277d
