########################################################################
# The Stack build, with dependencies based on a Stackage LTS snapshot.
#
# * If changing this file, usually cabal.project should be updated too.
#
# * When changing something here, check https://www.stackage.org/lts
#   for new releases, and update the resolver version to be the latest
#   in whichever series uses GHC 8.10.x.
#
# * After changing dependencies in stack.yaml or *.cabal, you must run
#   ./nix/regenerate.sh to update Nix files. Alternatively, let
#   Buildkite CI update the files for you.
#
########################################################################

resolver: lts-18.28
compiler: ghc-8.10.7

packages:
- lib/dbvar
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/numeric
- lib/text-class
- lib/test-utils
- lib/shelley
- lib/strict-non-empty-containers

flags:
  # Avoid a system library which causes difficulty with cross-compilation
  zip:
    disable-bzip2: true

  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

  # Using RDRAND instead of /dev/urandom as an entropy source for key
  # generation is dubious. Set the flag so we use /dev/urandom by default.
  cryptonite:
    support_rdrand: false

ghc-options:
  # Enable .hie file generation for weeder and haskell-language-server
  "$locals": -fwrite-ide-info

nix:
  shell-file: nix/stack-shell.nix
  # NOTE: Using a pure nix-shell (the default setting in Stack)
  # prevents environment variables from being passed down to tests.
  # If an environment variable needs to be set, add --env VAR=VAL
  # options on the test suite command line.
  pure: true

# This completely disables checking of Cabal file version bounds, and
# is necessary for Stack to successfully construct its build plan.
# When modifying dependencies, take note of the warnings.
allow-newer: true

extra-deps:
########################################################################
### cardano-wallet-specific dependencies

- OddWord-1.0.2.0
- command-0.1.1
- hspec-2.10.0
- hspec-core-2.10.0
- hspec-discover-2.10.0
- blockfrost-api-0.4.0.1
- blockfrost-client-0.4.0.1
- blockfrost-client-core-0.4.0.1
- quickcheck-quid-0.0.1
- servant-multipart-client-0.12.1
- aeson-2.0.2.0
- semialign-1.2.0.1
- tuples-0.1.0.0
- contiguous-0.6.2.0
- primitive-offset-0.2.0.0
- zigzag-0.0.1.0

# cardano-addresses-3.9.0
- git: https://github.com/input-output-hk/cardano-addresses
  commit: b9f424cc64459a95a2f190a1839ec9bc94cc778c
  subdirs:
    - command-line
    - core

########################################################################
### cardano-node 1.34.1 and its dependencies

- cryptonite-0.27 # 0.29 on lts-18.5 - constraint from ouroboros-consensus-byron
- Cabal-3.6.3.0 # 3.2.1.0 on lts-18.5
- containers-0.6.5.1 # 0.6.2.1 on lts-18.5
- dns-3.0.4 # 4.0.1 on lts-18.5
- network-3.1.2.7 # 3.1.1.1 on lts-18.5
- ral-0.1 # 0.2 on lts-18.5 - constraint from plutus-core
- recursion-schemes-5.2.2.2
- text-1.2.4.1 # 1.2.4.1 on lts-18.5
- Win32-2.6.2.0 # 2.6.1.0 on lts-18.5

# Not in LTS 18.5
- async-timer-0.2.0.0
- beam-core-0.9.1.0
- beam-migrate-0.5.1.0
- beam-sqlite-0.5.1.0
- canonical-json-0.6.0.0
- composition-prelude-3.0.0.2
- constraints-extras-0.3.2.1

- ip-1.7.4 # For cardano-sl-x509
- byteslice-0.2.7.0 # For ip
- bytesmith-0.3.8.0
- bytebuild-0.3.11.0
- natural-arithmetic-0.1.2.0
- run-st-0.1.1.0

- gray-code-0.3.1
- lazy-search-0.1.2.1
- lazysmallcheck-0.6
- libsystemd-journal-1.4.5
- markov-chain-usage-model-0.0.0
- micro-recursion-schemes-5.0.2.2
- monoidal-containers-0.6.2.0
- moo-1.2
- nothunks-0.1.3
- partial-order-0.2.0.0
- quickcheck-state-machine-0.7.1
- regex-posix-clib-2.7
- row-types-1.0.1.0
- servant-subscriber-0.7.0.0
- dom-lt-0.2.3
- secp256k1-haskell-0.6.1
- servant-websockets-2.0.0
- size-based-0.1.2.0
- statistics-linreg-0.3
- streaming-binary-0.2.2.0
- time-interval-0.1.1
- time-out-0.2
- hspec-golden-0.2.0.0
- transformers-except-0.1.2
- Unique-0.4.7.9


# Explicitly put back packages which were pruned by Stack.
- binary-0.8.8.0
- parsec-3.1.14.0

# Versions that differ in lts from those chosen by cabal
- OneTuple-0.3.1
- adjunctions-4.4.1
- algebraic-graphs-0.6
- ansi-terminal-0.11.3
- base-compat-0.12.1
- base-compat-batteries-0.12.1
- base16-0.3.2.0
- base64-bytestring-1.2.1.0
- base64-bytestring-type-1.0.1@rev:12
- bifunctors-5.5.12
- bin-0.1 # Older version lts had 0.1.1
- binary-orphans-1.0.2
- call-stack-0.4.0
- cborg-0.2.7.0
- conduit-extra-1.3.6
- deriving-compat-0.6.1
- either-5.0.2
- extra-1.7.10
- fast-logger-3.1.1
- fin-0.1.1 # Older version lts had 0.2
- fmt-0.6.1.2
- foldl-1.4.12@rev:3
- formatting-6.3.7
- free-5.1.8
- generic-arbitrary-0.2.2
- generic-lens-core-2.2.1.0
- generic-lens-2.2.1.0
- generic-random-1.5.0.1
- happy-1.20.0@rev:1
- hashable-1.3.5.0
- hedgehog-1.1.1
- hedgehog-quickcheck-0.1.1@rev:3
- hspec-golden-aeson-0.9.0.0
- http-api-data-0.4.3
- http-client-0.7.11
- http-client-tls-0.3.6.1
- http2-3.0.3
- indexed-traversable-instances-0.1.1
- invariant-0.5.6
- io-streams-haproxy-1.0.1.0@rev:5
- kan-extensions-5.2.4
- katip-0.8.7.1
- lattices-2.0.3
- lens-aeson-1.2.1
- lens-5.0.1
- list-t-1.0.5.2
- logict-0.8.0.0
- megaparsec-9.2.1
- memory-0.17.0
- microlens-0.4.13.0
- microlens-mtl-0.2.0.2
- microstache-1.0.2.1
- monad-logger-0.3.36@rev:2
- newtype-0.2.2.0@rev:3
- optics-core-0.4.1
- optics-extra-0.4.1
- optics-th-0.4.1
- optparse-applicative-0.17.0.0
- parsers-0.12.11
- parser-combinators-1.3.0
- persistent-2.13.3.5
- pipes-4.3.16@rev:3
- pipes-safe-2.3.4
- pretty-simple-4.1.0.0
- primitive-0.7.3.0@rev:2
- quickcheck-instances-0.3.27
- random-1.2.1.1
- regex-base-0.94.0.2@rev:1
- regex-posix-0.96.0.1@rev:1
- resourcet-1.2.5
- retry-0.9.2.0
- semigroups-0.19.2
- serialise-0.2.5.0
- servant-client-core-0.19
- servant-client-0.19
- servant-0.19
- servant-docs-0.12
- servant-multipart-api-0.12.1@rev:3
- servant-server-0.19.1
- snap-core-1.0.5.0@rev:1
- snap-server-1.1.2.0@rev:1
- statistics-0.16.1.0
- strict-list-0.1.7
- string-conv-0.2.0
- string-interpolate-0.3.1.2
- tasty-1.4.2.3
- tasty-hedgehog-1.2.0.0
- terminal-size-0.3.3
- text-conversions-0.3.1.1
- text-short-0.1.5
- th-compat-0.1.3@rev:1
- th-expand-syns-0.4.9.0
- time-compat-1.9.6.1
- typed-process-0.2.8.0@rev:1
- typerep-map-0.5.0.0
- universe-base-1.1.3
- unix-compat-0.5.4@rev:1
- unliftio-0.2.22.0
- unordered-containers-0.2.19.1
- vector-0.12.3.1@rev:2
- wai-app-static-3.1.7.4
- wai-extra-3.1.12.1
- wai-logger-2.4.0
- zlib-0.6.3.0

# Using a fork until our patches can be merged upstream

# TODO: ADP-1713
- git: https://github.com/biocad/servant-openapi3
  commit: 4165b837d3a71debd1059c3735460075840000b5

# TODO: ADP-1713
- git: https://github.com/paolino/openapi3
  commit: c30d0de6875d75edd64d1aac2272886528bc492d

- git: https://github.com/input-output-hk/optparse-applicative
  commit: 7497a29cb998721a9068d5725d49461f2bba0e7a

  # bech32-1.1.2
- git: https://github.com/input-output-hk/bech32
  commit: ab61914443e5f53624d3b2995767761b3f68e576
  subdirs:
  - bech32
  - bech32-th

- git: https://github.com/input-output-hk/cardano-base
  commit: 631cb6cf1fa01ab346233b610a38b3b4cba6e6ab
  subdirs:
  - base-deriving-via
  - binary
  - binary/test
  - cardano-crypto-class
  - cardano-crypto-praos
  - cardano-crypto-tests
  - orphans-deriving-via
  - slotting
  - strict-containers
  - measures

- git: https://github.com/input-output-hk/cardano-crypto
  commit: f73079303f663e028288f9f4a9e08bcca39a923e

- git: https://github.com/input-output-hk/cardano-ledger
  commit: e290bf8d0ea272a51e9acd10adc96b4e12e00d37
  subdirs:
  - eras/babbage/impl
  - eras/alonzo/impl
  - eras/alonzo/test-suite
  - eras/byron/chain/executable-spec
  - eras/byron/crypto
  - eras/byron/crypto/test
  - eras/byron/ledger/executable-spec
  - eras/byron/ledger/impl
  - eras/byron/ledger/impl/test
  - eras/shelley/impl
  - eras/shelley/test-suite
  - eras/shelley-ma/impl
  - eras/shelley-ma/test-suite
  - libs/cardano-ledger-core
  - libs/cardano-ledger-pretty
  - libs/cardano-protocol-tpraos
  - libs/cardano-data
  - libs/vector-map
  - libs/set-algebra
  - libs/small-steps
  - libs/small-steps-test
  - libs/non-integral

- git: https://github.com/input-output-hk/cardano-node
  commit: 95c3692cfbd4cdb82071495d771b23e51840fb0e
  subdirs:
  - cardano-api
  - cardano-cli
  - cardano-node
  - cardano-git-rev
  - trace-dispatcher
  - trace-resources
  - trace-forward


- git: https://github.com/input-output-hk/cardano-prelude
  commit: bb4ed71ba8e587f672d06edf9d2e376f4b055555
  subdirs:
  - cardano-prelude
  - cardano-prelude-test

  # In particular we rely on the code from this PR:
  # <https://github.com/input-output-hk/cardano-sl-x509/pull/6>
  # being merged.
- git: https://github.com/MELD-labs/cardano-sl-x509
  commit: 819997049b9cc675b28059d3d6f511d08f934d10

- git: https://github.com/input-output-hk/flat
  commit: ee59880f47ab835dbd73bea0847dab7869fc20d8

- git: https://github.com/input-output-hk/goblins
  commit: cde90a2b27f79187ca8310b6549331e59595e7ba

- git: https://github.com/input-output-hk/hedgehog-extras
  commit: edf6945007177a638fbeb8802397f3a6f4e47c14

- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: 066f7002aac5a0efc20e49643fea45454f226caa
  subdirs:
  - contra-tracer
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-ekg
  - plugins/backend-monitoring
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - tracer-transformers

- git: https://github.com/shmish111/purescript-bridge.git
  commit: 6a92d7853ea514be8b70bab5e72077bf5a510596

- git: https://github.com/input-output-hk/io-sim
  commit: f4183f274d88d0ad15817c7052df3a6a8b40e6dc
  subdirs:
    io-classes
    io-sim
    strict-stm

- git: https://github.com/input-output-hk/typed-protocols
  commit: 181601bc3d9e9d21a671ce01e0b481348b3ca104
  subdirs:
  - typed-protocols
  - typed-protocols-cborg
  - typed-protocols-examples

- git: https://github.com/input-output-hk/ouroboros-network
  commit: 04245dbd69387da98d3a37de9f400965e922bb0e
  subdirs:
  - monoidal-synchronisation
  - network-mux
  - ouroboros-consensus
  - ouroboros-consensus-test
  - ouroboros-consensus-byron
  - ouroboros-consensus-byronspec
  - ouroboros-consensus-byron-test
  - ouroboros-consensus-protocol
  - ouroboros-consensus-shelley
  - ouroboros-consensus-shelley-test
  - ouroboros-consensus-cardano
  - ouroboros-consensus-cardano-test
  - ouroboros-network
  - ouroboros-network-framework
  - ouroboros-network-testing
  # Extra packages not used by cardano-node but used by cardano-wallet
  - cardano-client
  - ntp-client
  - ouroboros-consensus-mock

- git: https://github.com/input-output-hk/plutus
  commit: d24a7540e4659b57ce2ab25dadb968991e232191
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - stubs/plutus-ghc-stub
    - prettyprinter-configurable
    - word-array

- git: https://github.com/input-output-hk/ekg-forward
  commit: 297cd9db5074339a2fb2e5ae7d0780debb670c63

- git: https://github.com/input-output-hk/cardano-config
  commit: 1646e9167fab36c0bff82317743b96efa2d3adaa

- git: https://github.com/shmish111/servant-purescript.git
  commit: a76104490499aa72d40c2790d10e9383e0dbde63

- git: https://github.com/input-output-hk/Win32-network
  commit: 3825d3abf75f83f406c1f7161883c438dac7277d

  # Until https://github.com/tibbe/ekg-json/pull/12 gets merged with aeson2 support
- git: https://github.com/vshabanov/ekg-json
  commit: 00ebe7211c981686e65730b7144fbf5350462608

- git: https://github.com/haskell-works/hw-aeson
  commit: d99d2f3e39a287607418ae605b132a3deb2b753f

