agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"
  STATE_DIR: "/var/lib/buildkite-agent/cache"
  STATE_DIR_MACOS: "/var/lib/buildkite-agent-hal-mac/cache"

steps:

  - block: "Refresh preprod node state (linux)"
    key: refresh-preprod-node-state-linux-block

  - label: 'Refresh preprod node state (linux)'
    depends_on: refresh-preprod-node-state-linux-block
    command: |
        cd ./scripts/buildkite/admin/ && nix develop -c ./refresh-preprod-snapshot.sh
    env:
      NODE_STATE_DIR: "${STATE_DIR?}/node/preprod"
    agents:
      system: x86_64-linux

  - block: "Refresh preprod node state (macOS)"
    depends_on: []
    key: refresh-preprod-node-state-macos-block

  - label: 'Refresh preprod node state (macOS)'
    depends_on: refresh-preprod-node-state-macos-block
    command: |
        cd ./scripts/buildkite/admin/ && nix develop -c ./refresh-preprod-snapshot.sh
    env:
      NODE_STATE_DIR: "${STATE_DIR_MACOS?}/node/preprod"
    agents:
      system: aarch64-darwin

  - block: Update artifacts history
    key: update-artifacts-csv-block
    depends_on: []

  - label: Update artifacts.csv
    depends_on: update-artifacts-csv-block
    command: |
        ./scripts/buildkite/admin/update-artifacts-csv.sh
    agents:
      system: x86_64-linux
    artifact_paths:
      - artifacts-history/artifacts.csv
