agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"
  STATE_DIR: "/var/lib/buildkite-agent/cache"

steps:

  - block: "Refresh preprod node state (linux)"
    key: refresh-preprod-node-state-linux-block

  - label: 'Refresh preprod node state (linux)'
    depends_on: refresh-preprod-node-state-linux-block
    command: |
        cd ./scripts/buildkite/admin/ && nix develop -c ./refresh-preprod-snapshot.sh
    env:
      NODE_STATE_DIR: "${STATE_DIR?}/node/preprod"
    agents:
      system: x86_64-linux
