env:
  NIX_PATH: "channel:nixos-19.03"
  BUILD_DIR: "/build/cardano-wallet"
  STACK_ROOT: "/build/cardano-wallet.stack"
  CACHE_DIR: "/cache/cardano-wallet"
  SCRATCH_DIR: "/scratch/cardano-wallet"

steps:
  - label: 'Restore benchmark - cardano mainnet'
    command: "./.buildkite/bench-restore.sh mainnet"
    env:
      HOME: "/cache/cardano-wallet.home"
    timeout_in_minutes: 600
    agents:
      system: x86_64-linux
      queue: benchmark

# Temporary disabled due to timing out (#2221)
#  - label: 'Restore benchmark - cardano testnet'
#    command: "./.buildkite/bench-restore.sh testnet"
#    env:
#      HOME: "/cache/cardano-wallet.home"
#    timeout_in_minutes: 600
#    agents:
#      system: x86_64-linux
#      queue: benchmark

  - label: 'Database benchmark'
    command: "./.buildkite/bench-db.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux
      queue: benchmark

  - label: 'Latency benchmark'
    command: "./.buildkite/bench-latency.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux
      queue: benchmark

  - label: 'Database Migrations Test'
    commands:
      - "rm -rf state-migration-test*"
      - "nix-build nix/migration-tests.nix -o migration-tests"
      - "./migration-tests/runall.sh"
    timeout_in_minutes: 60
    agents:
      system: x86_64-linux

  - wait

  - label: "Advance linux-tests-pass and all-tests-pass branches"
    command: "./.buildkite/push-branch.sh linux-tests-pass windows-tests-pass all-tests-pass"
    agents:
      system: x86_64-linux
