env:
  LC_ALL: "en_US.UTF-8"
  NIX_PATH: "channel:nixos-21.05"

  # Per-container variables
  SCRATCH_DIR: "/scratch/cardano-wallet"
  BUILD_DIR: "/build/cardano-wallet"
  STACK_ROOT: "/build/cardano-wallet.stack"
  CABAL_DIR: "/build/cardano-wallet.cabal"
  XDG_STATE_HOME: "/build/cardano-wallet/.state"
  XDG_CACHE_HOME: "/build/cardano-wallet/.cache"
  TESTS_LOGDIR: "/build/cardano-wallet/integration-test-logs"

  # Per-host variables - shared across containers on host
  CACHE_DIR: "/cache/cardano-wallet"

steps:
  - label: 'Restore benchmark - cardano mainnet'
    command: "./.buildkite/bench-restore.sh mainnet"
    env:
      HOME: "/cache/cardano-wallet.home"
    timeout_in_minutes: 600
    agents:
      system: x86_64-linux
      queue: benchmark
    if: 'build.env("step") == null || build.env("step") =~ /restore-mainnet/'

# Temporary disabled due to timing out (#2221)
#  - label: 'Restore benchmark - cardano testnet'
#    command: "./.buildkite/bench-restore.sh testnet"
#    env:
#      HOME: "/cache/cardano-wallet.home"
#    timeout_in_minutes: 600
#    agents:
#      system: x86_64-linux
#      queue: benchmark
#    if: 'build.env("step") == null || build.env("step") =~ /restore-testnet/'

  - label: 'Database benchmark'
    command: "./.buildkite/bench-db.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux
      queue: benchmark
    if: 'build.env("step") == null || build.env("step") =~ /bench-db/'

  - label: 'Latency benchmark'
    command: "./.buildkite/bench-latency.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux
      queue: benchmark
    if: 'build.env("step") == null || build.env("step") =~ /bench-latency/'

  # TODO: ADP-549 Port migrations test to shelley
  # - label: 'Database Migrations Test'
  #   commands:
  #     - "rm -rf state-migration-test*"
  #     - "nix-build nix/migration-tests.nix -o migration-tests"
  #     - "./migration-tests/runall.sh"
  #   timeout_in_minutes: 60
  #   agents:
  #     system: x86_64-linux
  #   if: 'build.env("step") == null || build.env("step") =~ /migration-tests/'

  - label: 'Full cabal build'
    command: 'nix-shell -A cabal --arg withCabalCache true --run "scripts/buildkite/cabal-ci.sh build"'
    env:
      CABAL_CACHE_ARCHIVE: "/cache/cardano-wallet"
      CABAL_STORE_DIR: "/build/cardano-wallet.store"
    agents:
      system: x86_64-linux
    if: 'build.env("step") == null || build.env("step") =~ /cabal/'

  - wait

  - label: "Advance linux-tests-pass and all-tests-pass branches"
    command: "./.buildkite/push-branch.sh linux-tests-pass windows-tests-pass all-tests-pass"
    agents:
      system: x86_64-linux
    if: 'build.env("step") == null'
