env:
  LC_ALL: "en_US.UTF-8"
  NIX_PATH: "channel:nixos-21.05"

  # Per-container variables
  SCRATCH_DIR: "/scratch/cardano-wallet"
  BUILD_DIR: "/build/cardano-wallet"
  STACK_ROOT: "/build/cardano-wallet.stack"
  CABAL_DIR: "/build/cardano-wallet.cabal"
  XDG_STATE_HOME: "/build/cardano-wallet/.state"
  XDG_CACHE_HOME: "/build/cardano-wallet/.cache"
  TESTS_LOGDIR: "/build/cardano-wallet/integration-test-logs"

  # Per-host variables - shared across containers on host
  CACHE_DIR: "/cache/cardano-wallet"

steps:
  - label: 'Prevent merging to wrong branch'
    if: 'build.branch == "bors/staging"'
    command: './.buildkite/check-bors.sh'
    agents:
      system: x86_64-linux
  - wait: ~
    if: 'build.branch == "bors/staging"'

  - label: 'Stack Rebuild'
    command:
      - "rm -rf $TESTS_LOGDIR && mkdir -p $TESTS_LOGDIR"
      - "nix-build .buildkite/default.nix -o sr"
      - "./sr/bin/rebuild --build-dir=$BUILD_DIR --cache-dir=$CACHE_DIR"
    timeout_in_minutes: 120
    artifact_paths:
      - "/build/cardano-wallet/.stack-work/logs/cardano-wallet*.log"
      - "/tmp/wallet-integration-logs/*/*.log"
    agents:
      system: x86_64-linux

  - label: 'Check Cabal Configure'
    command: 'nix-shell --pure -A cabal --run "scripts/buildkite/cabal-ci.sh configure"'
    agents:
      system: x86_64-linux

  - label: 'Check auto-generated Nix'
    key: nix
    commands:
      - './nix/regenerate.sh'
      - 'nix-build -A private.project.pkgs.checkStackProject -o check-stack-project.sh && ./check-stack-project.sh'
    agents:
      system: x86_64-linux

  - label: 'Check Cabal Configure (Haskell.nix shellFor)'
    depends_on: nix
    command:
      - 'nix-shell --run "echo --- Cabal update ; cabal update"'
      - 'nix-shell --run "echo +++ Cabal configure ; cabal configure --enable-tests --enable-benchmarks"'
      - 'nix-shell --run "echo +++ Cabal configure -frelease ; cabal configure -frelease --enable-tests --enable-benchmarks"'
    agents:
      system: x86_64-linux

  - label: 'Check Stylish Haskell'
    depends_on: nix
    command: 'nix-shell --run .buildkite/check-stylish.sh'
    agents:
      system: x86_64-linux

  - label: 'HLint'
    depends_on: nix
    command: 'nix-shell --run "echo +++ HLint ; hlint lib"'
    agents:
      system: x86_64-linux

  - label: 'Validate OpenAPI Specification'
    depends_on: nix
    command: 'nix-shell --run "echo +++ openapi-spec-validator ; openapi-spec-validator --schema 3.0.0 specifications/api/swagger.yaml"'
    agents:
      system: x86_64-linux

  - label: 'Docker Image'
    depends_on: nix
    command:
      - "nix-build .buildkite/docker-build-push.nix --argstr dockerHubRepoName inputoutput/cardano-wallet -o docker-build-push"
      - "./docker-build-push"
    agents:
      system: x86_64-linux
    soft_fail:
      - exit_status: '*'

  - label: 'TODO list'
    depends_on: nix
    command: 'nix-shell --run scripts/todo-list.sh'
    agents:
      system: x86_64-linux

  - label: 'Lint bash shell scripts'
    depends_on: nix
    commands:
      - 'echo +++ Shellcheck'
      - './scripts/shellcheck.sh'
    agents:
      system: x86_64-linux
