agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"

  # Per-host variables - shared across containers on host
  macos: "aarch64-darwin"
  linux: "x86_64-linux"


steps:
  - label: 'Merge from staging only'
    if: 'build.branch == "staging"'
    command: './.buildkite/check-bors.sh'
    agents:
      system: ${linux}

  - wait: ~
    if: 'build.branch == "staging"'

  - label: 'Check nix (linux)'
    # Check whether regenerate.sh was applied when it had to be applied.
    key: linux-nix
    commands:
      - './nix/regenerate.sh'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - block: "Run cabal release"
    if: '(build.branch !~ /^gh-readonly-queue\/master/) && (build.branch != "master") && (build.branch !~ /^release-candidate/)'
    depends_on: linux-nix
    key: cabal-release-block

  - label: 'Cabal build all -frelease'
    key: cabal-release
    depends_on: cabal-release-block
    command: |
      nix develop -c cabal update
      nix develop -c cabal build all -frelease
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Run unit tests (linux)'
    key: linux-tests-unit
    depends_on: linux-nix
    command: 'nix build -L .#ci.${linux}.tests.run.unit'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Run integration tests (linux)'
    key: linux-tests-integration
    command: 'nix build -L .#ci.${linux}.tests.run.integration'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Build benchmarks (linux)'
    key: build-benchmarks
    depends_on: linux-nix
    command: 'nix build .#ci.benchmarks.all'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Check Cabal Configure'
    key: cabal-configure
    depends_on: linux-nix
    command: 'nix develop --command scripts/buildkite/check-haskell-nix-cabal.sh'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Check code format'
    key: code-format
    depends_on: linux-nix
    command: 'nix develop --command .buildkite/check-code-format.sh'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Check HLint'
    key: hlint
    depends_on: linux-nix
    command: 'nix develop --command bash -c "echo +++ HLint ; hlint lib"'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Validate OpenAPI Specification'
    key: openapi
    depends_on: linux-nix
    command: 'nix develop --command bash -c "echo +++ openapi-spec-validator ; openapi-spec-validator --schema 3.0.0 specifications/api/swagger.yaml"'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Print TODO list'
    depends_on: linux-nix
    command: 'nix develop --command scripts/todo-list.sh'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Lint bash shell scripts'
    key: lint-bash
    depends_on: linux-nix
    commands:
      - 'echo +++ Shellcheck'
      - './scripts/shellcheck.sh'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Check HLS works'
    key: hls
    depends_on: linux-nix
    command: |
        nix develop --command bash -c "haskell-language-server lib/wallet/src/Cardano/Wallet.hs"
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - block: 'Run benchmark (api)'
    if: '(build.branch !~ /^gh-readonly-queue\/master/) && (build.branch != "master") && (build.branch !~ /^release-candidate/)'
    depends_on: linux-nix
    key: trigger-benchmark-api

  - label: 'Run benchmark (api)'
    command: "./.buildkite/bench-api.sh"
    depends_on: trigger-benchmark-api
    timeout_in_minutes: 20
    agents:
      system: x86_64-linux
    # We do not use the  benchmark  queue here, as we don't want
    # to use system resources that are intended for long-running processes
    # to perform quick-and-dirty benchmark runs.
    # queue: benchmark
    if: 'build.env("step") == null || build.env("step") =~ /bench-api/'
    env:
      TMPDIR: "/cache"

  - block: "macOS steps"
    if: '(build.branch !~ /^gh-readonly-queue\/master/) && (build.branch != "master") && (build.branch !~ /^release-candidate/)'
    depends_on: linux-nix
    key: trigger-macos

  - label: 'Check nix (macOS)'
    depends_on: trigger-macos
    key: macos-nix
    commands:
      - 'nix flake info'
    agents:
      system: ${macos}

  - label: 'Run unit tests (macOS, x86_64)'
    key: macos-tests-unit
    depends_on: macos-nix
    command: 'GC_DONT_GC=1 nix build --max-silent-time 0 --max-jobs 1 -L .#ci.x86_64-darwin.tests.run.unit'
    agents:
      system: ${macos}

  - label: 'Build package (macOS, x86_64)'
    key: macos-package
    depends_on: macos-nix
    command: nix build --max-silent-time 0 --max-jobs 1 -o result/macos-intel .#packages.x86_64-darwin.ci.artifacts.macos-intel.release
    artifact_paths: [ "./result/macos-intel/**" ]
    agents:
      system: ${macos}

  - block: "Build package (linux)"
    depends_on: linux-nix
    if: '(build.branch !~ /^gh-readonly-queue\/master/) && (build.branch != "master") && (build.branch !~ /^release-candidate/)'
    key: trigger-build-linux-package

  - label: 'Build package (linux)'
    key: linux-package
    depends_on: [linux-nix, trigger-build-linux-package]
    command: nix build -o result/linux .#ci.artifacts.linux64.release
    artifact_paths: [ "./result/linux/**" ]
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - block: "Build windows artifacts"
    depends_on: linux-nix
    if: '(build.branch !~ /^gh-readonly-queue\/master/) && (build.branch != "master") && (build.branch !~ /^release-candidate/)'
    key: trigger-build-windows-artifacts

  - label: 'Build package (windows)'
    key: windows-package
    depends_on: [linux-nix, trigger-build-windows-artifacts]
    command: nix build -o result/windows .#ci.artifacts.win64.release
    artifact_paths: [ "./result/windows/**" ]
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Build testing bundle (windows)'
    key: windows-testing-bundle
    depends_on: [linux-nix, trigger-build-windows-artifacts]
    command: nix build -o result/windows-tests .#ci.artifacts.win64.tests
    artifact_paths: [ "./result/windows-tests/**" ]
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - block: "Run E2E tests"
    if: '(build.branch !~ /^gh-readonly-queue\/master/) && (build.branch != "master") && (build.branch !~ /^release-candidate/)'
    depends_on: linux-nix
    key: trigger-e2e-tests

  - label: "Run E2E tests"
    key: e2e
    depends_on: trigger-e2e-tests
    command: 'nix develop --command bash -c "just e2e-local"'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: Manage rc-latest tags
    depends_on:
      - cabal-release
      - linux-tests-unit
      - linux-tests-integration
      - cabal-configure
      - code-format
      - hlint
      - openapi
      - lint-bash
      - hls
      - build-benchmarks
      - macos-tests-unit
      - macos-package
      - linux-package
      - windows-package
      - windows-testing-bundle
      - e2e
    if: '(build.branch =~ /^release-candidate/)' #build.branch =~ /\/feature$$/
    command: .buildkite/retag-rc-latest.sh
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"
