agents:
  queue: cardano-wallet

env:
  windows: "windows-x64"

steps:
  - label: "Windows TLS diagnostic (extended)"
    command: "powershell.exe -ExecutionPolicy Bypass -File scripts\\buildkite\\windows\\tls-diagnostic.ps1"
    agents:
      system: ${windows}
