agents:
  queue: cardano-wallet

env:
  windows: "windows-x64"

steps:
  - label: "Windows TLS diagnostic (extended)"
    command: "powershell.exe -ExecutionPolicy Bypass -File scripts\\buildkite\\windows\\tls-diagnostic.ps1"
    agents:
      system: ${linux}

  - label: Dev Shell Attic Cache (linux)
    depends_on:
      - linux-nix
    commands:
      - nix develop path:$MAIN_PIPELINE_DIR -c $MAIN_PIPELINE_DIR/attic-cache.sh
    agents:
      system: ${linux}
    env:
      system: ${linux}

  - label: Check Nix (macOS)
    if: build.branch != "ci/gha-linux-unit-tests"
    key: macos-nix
    commands:
        - nix --version
        - nix flake info
    agents:
      system: ${macos}

  - label: Dev Shell Attic Cache (macos)
    if: build.branch != "ci/gha-linux-unit-tests"
    depends_on:
      - macos-nix
    commands:
      - nix develop path:$MAIN_PIPELINE_DIR -c $MAIN_PIPELINE_DIR/attic-cache.sh
    agents:
      system: ${macos}
    env:
      system: ${macos}

  - group: Linux Checks
    if: build.branch != "ci/gha-linux-unit-tests" && (build.env("RELEASE_CANDIDATE") == null || build.env("TEST_RC") == "FALSE")
    key: linux-tests
    depends_on:
      - linux-nix
    steps:

    - block: Run E2E Tests (linux)
      if: build.env("RELEASE_CANDIDATE") == null
      depends_on: []
      key: trigger-e2e-tests

    - label: Run Linux E2E Tests (linux)
      depends_on:
        - trigger-e2e-tests
      commands: |
        nix shell 'nixpkgs#just' -c just e2e
      artifact_paths:
      env:

      agents:
        system: ${linux}
      concurrency: 1
      concurrency_group: 'linux-e2e-tests'

    - block: Mainnet Boot Sync with Mithril
      if: build.env("RELEASE_CANDIDATE") == null && build.branch != "master"
      depends_on: []
      key: linux-mainnet-full-sync-block

    - label: Mainnet Boot Sync with Mithril
      soft_fail :
        - exit_status: 44
      depends_on:
        - linux-mainnet-full-sync-block
      command: |
        cd run/mainnet/nix
        rm -rf logs
        mkdir -p logs
        rm -rf databases
        ./snapshot.sh
        ./run.sh sync 7200
      artifact_paths:
        - "./run/mainnet/nix/logs/*"
      agents:
        system: x86_64-linux
      env:
        SUCCESS_STATUS: ready
        NODE_LOGS_FILE: ./logs/node.log
        WALLET_LOGS_FILE: ./logs/wallet.log
        CLEANUP_DB: true
        NETWORK: mainnet
      concurrency: 1
      concurrency_group: 'mithril-mainnet-full-sync'

  - group: MacOS Artifacts
    if: build.branch != "ci/gha-linux-unit-tests"
    key: macos-artifacts
    depends_on: macos-nix
    steps:

    - block: MacOS Artifacts
      if: |
        build.branch !~ /^gh-readonly-queue\/master/
          && build.branch != "master"
          && build.env("RELEASE_CANDIDATE") == null
      key: block-macos

    - label: Build Integration Tests (macOS, arm64)
      key: macos-arm64-tests-build-integration
      if: build.env("TEST_RC") == null || build.env("TEST_RC") == "FALSE"
      depends_on: block-macos
      command: nix build -L .#packages.aarch64-darwin.integration-exe
      agents:
        system: ${macos}
        queue: "cardano-wallet"

    - label: Build Package (macOS, x86_64)
      key: macos-intel-package
      depends_on: block-macos
      command: 'nix build -L -o result/macos-intel .#packages.x86_64-darwin.ci.artifacts.macos-intel.release'
      artifact_paths: [ "./result/macos-intel/**" ]
      agents:
        system: ${macos}

    - label: Build Package (macOS, arm64)
      key: macos-arm64-package
      depends_on: block-macos
      command: 'nix build -L -o result/macos-silicon .#packages.aarch64-darwin.ci.artifacts.macos-silicon.release'
      artifact_paths: [ "./result/macos-silicon/**" ]
      agents:
        system: ${macos}

  - group: MacOS Checks
    key: "macos-checks"
    if: build.branch != "ci/gha-linux-unit-tests" && (build.env("RELEASE_CANDIDATE") == null || build.env("TEST_RC") == "FALSE")
    depends_on:
      - macos-artifacts
    steps:

    - block: MacOS Unit Tests
      if: |
        build.branch !~ /^gh-readonly-queue\/master/
          && build.branch != "master"
          && build.env("RELEASE_CANDIDATE") == null
      depends_on: []
      key: macos-unit-tests-block

    - label: Run Unit Tests (macOS, x86_64)
      if: 0 == 1 # https://github.com/cardano-foundation/cardano-wallet/issues/5049
      key: macos-intel-tests-run-unit
      depends_on: macos-unit-tests-block
      command: 'nix build -L .#ci.x86_64-darwin.tests.run.unit'
      agents:
        system: ${macos}

    # macOS unit tests - run each suite with memory limits
    - label: "Unit (macOS): cardano-wallet-application-tls"
      <<: *macos_unit_test
      command: cd lib/application-tls && nix run ../../.#unit-cardano-wallet-application-tls -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-balance-tx"
      <<: *macos_unit_test
      command: cd lib/balance-tx && nix run ../../.#unit-cardano-balance-tx -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-numeric"
      <<: *macos_unit_test
      command: nix run .#unit-cardano-numeric -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-wallet-blackbox-benchmarks"
      <<: *macos_unit_test
      command: nix run .#unit-cardano-wallet-blackbox-benchmarks -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-wallet-launcher"
      <<: *macos_unit_test
      command: nix run .#unit-cardano-wallet-launcher -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-wallet-network-layer"
      <<: *macos_unit_test
      command: nix run .#unit-cardano-wallet-network-layer -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-wallet-primitive"
      <<: *macos_unit_test
      command: cd lib/primitive && nix run ../../.#unit-cardano-wallet-primitive -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-wallet-secrets"
      <<: *macos_unit_test
      command: nix run .#unit-cardano-wallet-secrets -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): cardano-wallet-test-utils"
      <<: *macos_unit_test
      command: nix run .#unit-cardano-wallet-test-utils -- +RTS -M2G -s -RTS

    # cardano-wallet-unit split by test module prefix
    - label: "Unit (macOS): wallet-unit / Byron + CLI"
      <<: *macos_unit_test
      # CLI tests need golden files from lib/unit/test/data
      command: cd lib/unit && nix shell ../../.#cardano-cli -c nix run ../../.#unit-cardano-wallet-unit -- --match "/Cardano.Byron./" --match "/Cardano.CLI/" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / DB.Sqlite + Pool"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.DB./" --match "/Cardano.Pool./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / Address"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.Wallet.Address./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / Api"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.Wallet.Api./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / Balance"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.Wallet.Balance./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / DB"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.Wallet.DB./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / Primitive"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.Wallet.Primitive./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / Shelley"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.Wallet.Shelley./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / Other Wallet"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Cardano.Wallet./" --skip "/Cardano.Wallet.Address./" --skip "/Cardano.Wallet.Api./" --skip "/Cardano.Wallet.Balance./" --skip "/Cardano.Wallet.DB./" --skip "/Cardano.Wallet.Primitive./" --skip "/Cardano.Wallet.Shelley./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): wallet-unit / Control + Data"
      <<: *macos_unit_test
      command: nix shell .#cardano-cli -c nix run .#unit-cardano-wallet-unit -- --match "/Control./" --match "/Data./" -j1 +RTS -M2G -s -RTS

    - label: "Unit (macOS): delta-chain"
      <<: *macos_unit_test
      command: nix run .#unit-delta-chain -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): delta-store"
      <<: *macos_unit_test
      command: nix run .#unit-delta-store -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): delta-table"
      <<: *macos_unit_test
      command: nix run .#unit-delta-table -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): delta-types"
      <<: *macos_unit_test
      command: nix run .#unit-delta-types -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): std-gen-seed"
      <<: *macos_unit_test
      command: nix run .#unit-std-gen-seed -- +RTS -M2G -s -RTS

    - label: "Unit (macOS): wai-middleware-logging"
      <<: *macos_unit_test
      command: nix run .#unit-wai-middleware-logging -- +RTS -M2G -s -RTS

    - block: MacOS Integration Tests
      # if: build.env("RELEASE_CANDIDATE") == null
      depends_on: []
      key: macos-integration-tests-block

    - label: Run Integration Tests (macOS)
      key: macos-tests-integration
      depends_on: macos-integration-tests-block
      command: nix shell 'nixpkgs#just' -c just conway-integration-tests 2
      agents:
        system: ${macos}
        queue: "cardano-wallet"
      concurrency: 3
      concurrency_group: 'macos-integration-tests'

    - block: MacOS E2E Tests
      if: build.env("RELEASE_CANDIDATE") == null || build.env("TEST_RC") == "TRUE"
      depends_on: []
      key: macos-e2e-tests-block

    - label: 'Run E2E Tests (macOS, arm64)'
      key: macos-silicon-e2e
      depends_on:
        - macos-e2e-tests-block
      commands: |
        nix shell 'nixpkgs#just' -c just e2e
      agents:
        system: ${macos}
      concurrency: 1
      concurrency_group: 'macos-e2e-tests'

  # TODO: Windows builds disabled pending #5107 (OOM) and #5110 (TLS)
  # - group: Windows Artifacts
  #   key: windows-artifacts
  #   depends_on:
  #     - linux-nix
  #   steps:
  #   - block: Build Windows Artifacts (windows)
  #     depends_on: []
  #     if: |
  #       build.branch !~ /^gh-readonly-queue\/master/
  #         && build.branch != "master"
  #         && build.branch != "rc-latest"
  #         && build.env("RELEASE_CANDIDATE") == null
  #     key: trigger-build-windows-artifacts
  #
  #   - label: Build Package (windows)
  #     key: windows-package
  #     depends_on:
  #       - trigger-build-windows-artifacts
  #     command: nix build -L -o result/windows .#ci.artifacts.win64.release
  #     artifact_paths: [ "./result/windows/**" ]
  #     agents:
  #       system: ${linux}
  #
  #   - label: Build Testing Bundle (windows)
  #     key: windows-testing-bundle
  #     depends_on:
  #       - trigger-build-windows-artifacts
  #     command: |
  #       nix build -L -o result .#ci.artifacts.win64.tests
  #       cp result/cardano-wallet-*-tests-win64.zip ./windows-tests.zip
  #     artifact_paths: [ "./windows-tests.zip"]
  #     agents:
  #       system: ${linux}
  #
  # - group: Windows Checks
  #   depends_on:
  #     - windows-artifacts
  #   steps:
  #   - label: Windows Unit Tests
  #     commands:
  #       - buildkite-agent artifact download "windows-tests.zip" .
  #       - mkdir -p windows\tests
  #       - tar -xf windows-tests.zip -C windows\tests
  #       - cd windows\tests
  #       - .\cardano-wallet-unit-test-unit.exe --color --jobs 1 --skip /Cardano.Wallet.DB.Sqlite/ +RTS -N2
  #     agents:
  #       system: ${windows}
  #     env:
  #       LOCAL_CLUSTER_CONFIGS: test\data\cluster-configs
  #     concurrency: 1
  #     concurrency_group: 'windows-tests'
  #
  #   - label: Windows Text Class Tests
  #     command: |
  #       buildkite-agent artifact download "windows-tests.zip" .
  #       mkdir windows-tests
  #       tar -xf windows-tests.zip -C windows-tests
  #       .\windows-tests\text-class-test-unit.exe --color
  #     agents:
  #       system: ${windows}
  #     concurrency: 1
  #     concurrency_group: 'windows-tests'
  #
  #   - block: Windows E2E Tests
  #     depends_on: []
  #     if: build.env("RELEASE_CANDIDATE") == null || build.env("TEST_RC") == "TRUE"
  #     key: trigger-windows-e2e-tests
  #
  #   - label: ⚙️ Windows E2E Tests
  #     timeout_in_minutes: 120
  #     depends_on:
  #       - trigger-windows-e2e-tests
  #     commands:
  #       - diff -r configs/cardano/preprod lib/integration/configs/cardano/preprod
  #       - buildkite-agent artifact download "windows-tests.zip" .
  #       - mkdir windows-tests
  #       - tar -xf windows-tests.zip -C windows-tests
  #       - .\windows-tests\cardano-wallet-integration-test-e2e.exe
  #     agents:
  #       system: ${windows}
  #     concurrency: 1
  #     concurrency_group: 'windows-tests'

