agents:
  queue: cardano-wallet

env:
  windows: "windows-x64"

steps:
  - label: "Windows TLS cert store diagnostic"
    command: |
      Write-Host "=== Local Machine ROOT store (USERTrust) ==="
      Get-ChildItem Cert:\LocalMachine\Root | Where-Object { $$_.Subject -match "USERTrust" } | Format-List Subject, Thumbprint, NotAfter
      Write-Host "=== Current User ROOT store (USERTrust) ==="
      Get-ChildItem Cert:\CurrentUser\Root | Where-Object { $$_.Subject -match "USERTrust" } | Format-List Subject, Thumbprint, NotAfter
      Write-Host "=== Local Machine ROOT store (all certs count) ==="
      (Get-ChildItem Cert:\LocalMachine\Root).Count
      Write-Host "=== Current User ROOT store (all certs count) ==="
      (Get-ChildItem Cert:\CurrentUser\Root).Count
    agents:
      system: ${windows}
