agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"
  STATE_DIR: "/var/lib/buildkite-agent/cache"
  STATE_DIR_MACOS: "/var/lib/buildkite-agent-hal-mac/cache"

  linux: "x86_64-linux"
  macos: "aarch64-darwin"

steps:
  - label: Add release commits
    key: add-release-commits
    commands: |
      ./scripts/buildkite/release/release-candidate.sh
    agents:
      system: x86_64-linux

  - label: "Generate and upload trigger step to main pipeline"
    depends_on: add-release-commits
    commands:
      - ./scripts/buildkite/release/generate-trigger.sh | buildkite-agent pipeline upload
