agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"
  NODE_STATE_DIR: "/var/lib/buildkite-agent/cache/preprod/node_db"


steps:
  - label: Add release commits
    key: add-release-commits
    commands: |
      ./scripts/buildkite/release/release-candidate.sh
    agents:
      system: x86_64-linux

  - label: 'Refresh node state'
    key: refresh-node-state
    command:
      - ./scripts/buildkite/release/fetch-preprod-snapshot.sh
    agents:
      system: x86_64-linux
