agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"
  STATE_DIR: "/var/lib/buildkite-agent/cache"

steps:
  - label: Add release commits
    key: add-release-commits
    commands: |
      ./scripts/buildkite/release/release-candidate.sh
    agents:
      system: x86_64-linux

  - label: 'Build package (linux)'
    key: linux-package
    depends_on: add-release-commits
    command:
      - ./scripts/buildkite/release/linux-package.sh
    artifact_paths: [ "./result/linux/**" ]
    agents:
      system: x86_64-linux

  - label: 'Build Docker Image'
    key: build-docker
    depends_on:
      - add-release-commits
    commands:
      ./scripts/buildkite/release/docker-build.sh
    agents:
      system: x86_64-linux

  - label: 'Run linux e2e tests'
    depends_on:
      - add-release-commits
      - linux-package
    commands: |
      ./scripts/buildkite/release/linux-e2e.sh
    artifact_paths:
      - "./result/linux/**"
      - "./logs/**/*"
    env:
      NODE_STATE_DIR: "${STATE_DIR?}/node/preprod"
    agents:
      system: x86_64-linux
