agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"
  STATE_DIR: "/var/lib/buildkite-agent/cache"
  STATE_DIR_MACOS: "/var/lib/buildkite-agent-hal-mac/cache"
  RELEASE_SCRIPTS_DIR: "./scripts/buildkite/release"

  linux: "x86_64-linux"
  macos: "aarch64-darwin"

steps:
  - label: Add release commits
    key: add-release-commits
    commands: |
      ./scripts/buildkite/release/release-candidate.sh
    agents:
      system: x86_64-linux

  - label: "Generate and upload trigger step to main pipeline"
    depends_on: add-release-commits
    commands:
      - ./scripts/buildkite/release/generate-trigger.sh | buildkite-agent pipeline upload

  - group : Nightly
    key: nightly
    depends_on: main-pipeline-build
    steps:
      - label: Push swagger nightly
        commands:
          - nix develop path:$RELEASE_SCRIPTS_DIR -c $RELEASE_SCRIPTS_DIR/push-to-bump.sh
        artifacts:
          - artifacts/api-diffs.md
        env:
          RELEASE: false
        agents:
          system: x86_64-linux

      - label: Push nightly release tag
        key: push-nightly-tag
        commands:
          - nix develop path:$RELEASE_SCRIPTS_DIR -c $RELEASE_SCRIPTS_DIR/push-nightly-tag.sh
        agents:
          system: x86_64-linux

      - label: Push nightly release
        depends_on: push-nightly-tag
        key: push-nightly-release
        commands:
          - nix develop path:$RELEASE_SCRIPTS_DIR -c $RELEASE_SCRIPTS_DIR/push-nightly-release.sh
        agents:
          system: x86_64-linux

      - label: Push nightly release artifacts
        depends_on: push-nightly-release
        commands:
          - nix develop path:$RELEASE_SCRIPTS_DIR -c $RELEASE_SCRIPTS_DIR/push-nightly-artifacts.sh
        agents:
          system: x86_64-linux

  - group: Release
    depends_on: nightly
    if: build.branch == "master"
    steps:
      - block: Create a release
        key: create-release

      - label: Push swagger release
        depends_on: create-release
        commands:
          - nix develop path:$RELEASE_SCRIPTS_DIR -c $RELEASE_SCRIPTS_DIR/push-to-bump.sh
        artifacts:
          - artifacts/api-diffs.md
        env:
          RELEASE: true
        agents:
          system: x86_64-linux