agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"

steps:
  - label: Add release commits
    key: add-release-commits
    commands: |
      ./scripts/buildkite/release/release-candidate.sh
    agents:
      system: x86_64-linux

  - label: 'Build package (linux)'
    key: linux-package
    depends_on: add-release-commits
    command:
      - ./scripts/buildkite/release/linux-package.sh
    artifact_paths: [ "./result/linux/**" ]
    agents:
      system: ${linux}

