agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"
  STATE_DIR: "/var/lib/buildkite-agent/cache"

    # Per-host variables - shared across containers on host
  linux: "x86_64-linux"

steps:
  - input: Restoration Benchmark
    if: build.branch != "master"
    key: restoration-parameters
    fields:
      - select: "Node Sync Timeout"
        hint: "Possible timeout in hours until node is synced"
        key: "to-tip-timeout"
        default: "infinite"
        options:
        - label: "Infinite"
          value: "infinite"
        - label: "4"
          value: "4"
        - label: "1"
          value: "1"
        - label: "2"
          value: "2"

  - label: Nix build on benchmark queue (linux)
    key: nix-build-benchmarks
    depends_on: restoration-parameters
    command:
      - nix build -L
      - nix build -L .#ci.benchmarks.all
    agents:
      system: ${linux}
      queue: adrestia-bench

  - label: Restore benchmark baseline (linux)
    command: |
      nix develop path:./scripts/buildkite/main --command bash -c \
        "./scripts/buildkite/main/bench-restore.sh mainnet base $HOME/databases/node/mainnet-1"
    depends_on:
      - restoration-parameters
    timeout_in_minutes: 1380
    agents:
      system: ${linux}
      queue: adrestia-bench
    concurrency: 1
    concurrency_group: 'restoration-benchmarks-1'
