name: 🆕 Suggest an improvement or new feature
description: How could cardano-wallet be improved?
labels: ["IMPROVEMENT", "ADDING FEATURE"]
body:
  - type: textarea
    attributes:
      label: Why?
      description: >-
        Please describe your situation or application and what you
        would like to achieve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What?
      description: >-
        What feature or improvement currently missing would help you
        achieve your goal.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How?
      description: >-
        If you have any suggestions for how to implement this
        improvement, please add them.

        If you have a way to work around a missing feature, include
        that info here.
