# this is a default logging configuration of cli

# global filter; messages must have at least this severity to pass:
minSeverity: Debug

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: StdoutSK
    scFormat: ScText
    scName: text
  - scKind: StdoutSK
    scFormat: ScJson
    scName: json

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - StdoutSK
    - text

# this is probably a bug of parsing, cannot enforce cgBindAddrPrometheus = Nothing
#hasPrometheus: ["",0]
#hasPrometheus:

# these backends are initialized:
setupBackends: [AggregationBK, KatipBK]

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# more options which can be passed as key-value pairs:
options:
  mapSubtrace:
    "#messagecounters.monitoring":
      subtrace: NoTrace
    "#messagecounters.ekgview":
      subtrace: NoTrace
    "#messagecounters.aggregation":
      subtrace: NoTrace
    "#messagecounters.graylog":
      subtrace: NoTrace
    "#messagecounters.katip":
      subtrace: NoTrace
    "#messagecounters.switchboard":
      subtrace: NoTrace
