#!/usr/bin/env bash

################################################################################
# Generates a "direct" cradle config for ghcide. Use this if you want
# faster reloads and cross-package jump-to-definition. It needs to be
# run from the nix-shell.
################################################################################

set -euo pipefail

out=hie-direct.yaml
ghci=custom.ghci
builddir=dist-newstyle
plan_json=$builddir/cache/plan.json
packages=$(basename -a $(git ls-files '*.cabal') | sed 's/\.cabal//')
version=$(awk '/^version:/ { print $2; }' lib/core/cardano-wallet-core.cabal)

list_sources() {
  git ls-files 'lib/**/*.hs' | grep -v Main.hs
}

query_plan_json() {
  jq -r '.["install-plan"][]|select(."pkg-name"=="'$1'")|select(.["component-name"]=="'$2'")["'$3'"]' < $plan_json
}

get_dist_dir() {
  relpath $(query_plan_json $1 lib dist-dir)
}

get_bin_dir() {
  dirname $(relpath $(query_plan_json $1 $2 bin-file))
}

relpath() {
  realpath --relative-to=$(pwd) $1
}

echo "Generating $out. Some cabal builds may be necessary."

cabal="cabal --project-file=cabal-nix.project --builddir=$builddir"

test -f $plan_json || $cabal configure

echo "# Generated by $0 for $version on $(date)" > $out

cat >> $out <<EOF
cradle:
  multi:
    - path: "./lib"
      config:
        cradle:
          direct:
            arguments:
              - -XOverloadedStrings
              - -XNoImplicitPrelude
              - -XTypeApplications
              - -XDataKinds
              - -fwarn-unused-binds
              - -fwarn-unused-imports
              - -fwarn-orphans
              - -Wno-missing-home-modules
EOF

dirname $(list_sources) | sed -e 's/^\([^A-Z]*\).*$/              - -i\1/' | sed 's=/$==' | sort -u >> $out
list_sources | sed -e 's/^[^A-Z]*\(.*\)\.hs$/\1/' | grep / | sed 'y=/=.=' | sed 's/^/              - /' >> $out

for pkg in $packages; do
  echo "              - Paths_$(echo $pkg | sed y/-/_/)" >> $out
  echo "              - -i$(get_dist_dir $pkg)/build/autogen" >> $out
done

cat >> $out <<EOF

    - path: "."
      config: {cradle: {none: }}
EOF

echo "-- Generated by $0 for $version on $(date)" > $ghci

cat >> $ghci <<EOF
:set prompt "λ "
:set -fwarn-unused-binds
:set -fwarn-unused-imports
:set -Wno-missing-home-modules
:set -XOverloadedStrings
:set -XNoImplicitPrelude
:set -XTypeApplications -XDataKinds

import Prelude
import System.Environment (setEnv, getEnv)
import System.Directory (getCurrentDirectory)

getCurrentDirectory >>= \d -> getEnv "PATH" >>= \p -> setEnv "PATH" (d ++ "$(get_bin_dir cardano-wallet exe:cardano-wallet):" ++ p)

EOF

dirname $(git ls-files 'lib/**/*.hs' | grep -v Main.hs) | sed -e 's/^\([^A-Z]*\).*$/:set -i\1/' | sed 's=/$==' | sort -u | grep -v lib/jormungandr/test/integration >> $ghci

for pkg in $packages; do
  echo ":set -i$(get_dist_dir $pkg)/build/autogen" >> $ghci
done

echo "Finished. Type the following to enable your config:"
echo "  ln -sf hie-direct.yaml hie.yaml"
echo "  ln -sf custom.ghci .ghci"
