#!/usr/bin/env bash

# Constructs a CHANGELOG using every PR merged since a given date. It groups PRs by milestones.
#
# /!\ depends on 'jq' and 'curl' /!\
#
# Usage:
#     make_changelog YYYY-MM-DD
#
# Example:
#     make_changelog 2019-08-15

# NOTE:
# You need to set $API_TOKEN before running this script

REPO="input-output-hk/cardano-wallet"

PULL_REQUESTS=$(curl -X GET \
  -H "Authorization: token $GITHUB_API_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/search/issues?per_page=500\&q=repo:$REPO+is:pr+is:merged+merged:%3E$1)

PULL_REQUESTS=$(echo $PULL_REQUESTS | jq '.items | map({number:.number,title:.title,milestone:.milestone.title}) | group_by(.milestone)')
ITEMS=$(echo $PULL_REQUESTS | jq 'map(map("#\(.number) | \(.title)"))')
MILESTONES=$(echo $PULL_REQUESTS | jq 'map(map("\(.milestone)") | unique) | flatten')
I=($(echo $MILESTONES | jq 'length - 1'))

for i in $(seq 0 $I); do
  MILESTONE=$(echo $MILESTONES | jq -r ".[$i]")
  echo "<details>"
  echo "    <summary>$MILESTONE</summary>"
  echo ""
  echo "PR | Description"
  echo "-- | --"
  J=($(echo $ITEMS | jq ".[$i] | length - 1"))
  for j in $(seq 0 $J); do
    LINE=$(echo $ITEMS | jq -r ".[$i] | .[$j]")
    echo "$LINE"
  done
  echo "</details>"
done
