ENV['NODE_DB'] ||= "./node_db"
ENV['WALLET_DB'] ||= "./wallet_db"
ENV['LOGS'] ||= "./logs"
ENV['BINS'] ||= "./bins"
ENV['FIXTURE_WALLETS'] ||= "./fixture_wallets.json"
ENV['TOKEN_METADATA'] ||= "https://metadata.cardano-testnet.iohkdev.io/"
