source 'https://rubygems.org'

gem 'cardano_wallet', '~> 0.3.17'
# gem 'cardano_wallet', path: "~/wb/cardano_wallet"
gem 'bip_mnemonic', '0.0.4'
gem 'rake', '12.3.3'
gem 'rspec', '3.10.0'
gem 'mustache', '1.1.1'
gem 'blake2b', '0.10.0'
gem 'cbor', '0.5.9.6'
