# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cardano_wallet', '~> 0.4.2'
# gem 'cardano_wallet', path: "~/wb/cardano_wallet"
gem 'blake2b', '0.10.0'
gem 'buildkit', '1.5'
gem 'cbor', '0.5.9.8'
gem 'mustache', '1.1.1'
gem 'rake', '12.3.3'
gem 'rspec', '3.11.0'
