name: Docker-compose MacOS
on:
  schedule:
  - cron:  "0 23 * * *"
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.2.0
      - run: |
            brew install docker
            brew install docker-compose

            mkdir -p ~/.docker/cli-plugins \
                ln -sfn $HOMEBREW_PREFIX/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose

      - uses: ruby/setup-ruby@v1.127.0
        with:
          ruby-version: 2.7.1
      - name: Install cardano_wallet gem
        run: gem install cardano_wallet
      - name: Check docker-compose
        run: |
          docker compose up -d
          ./scripts/connect_wallet.rb
        env:
          NETWORK: preprod
  report:
    needs: [build]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification on failure
      if: needs.build.result == 'failure'
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_ICON_EMOJI: ':poop:'
          SLACK_USERNAME: 'GitHub Action'
          SLACK_MESSAGE: |
              *Job Link:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_COLOR: '#FF0000'

    - name: Slack Notification on success
      if: needs.build.result == 'success'
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_USERNAME: 'GitHub Action'
          SLACK_MESSAGE: |
              *Job Link:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_COLOR: '#00FF00'
